listen_interface: 127.0.0.1
listen_port: 8080
target: http://127.0.0.1:9200
json_logging: false
anonymous_group: group1
group_header_name: X-Remote-Groups
group_header_type: AD
user_header_name: X-Remote-User

rbac:
  groups:
    group1:
      whitelisted_indices:
        - name: secret_stuff
          rest_verbs:
          - GET
          - POST

        ### req'd for kibana
        - name: .kibana
          rest_verbs:
          - GET
          - POST

      # YAML supports pointers
      whitelisted_apis: *kibana

      can_manage: false

    group2:
      can_manage: true
      whitelisted_indices:
        - name: test_deflek
          rest_verbs:
          - GET
          - POST
        - name: test_deflek2
          rest_verbs:
          - GET
        - name: globby-*
          rest_verbs:
          - GET

        ### req'd for kibana
        - name: .kibana
          rest_verbs:
          - GET
          - POST

      # you can reuse this declaration with a YAML pointer
      whitelisted_apis: &kibana
        - name: _nodes
          rest_verbs:
          - GET
        - name: _msearch
          rest_verbs: ["POST"]
        - name: _all
          rest_verbs: ["GET", "POST"]
        - name: _search
          rest_verbs: ["GET", "POST"]
        - name: _mget
          rest_verbs: ["POST"]
        - name: _mappings
          rest_verbs: ["GET"]
        - name: _mapping
          rest_verbs: ["GET"]
        - name: _local
          rest_verbs: ["GET"]
        - name: _aliases
          rest_verbs: ["GET"]
        - name: _field_stats
          rest_verbs: ["POST"]
        - name: _nodes
          rest_verbs: ["GET"]
        # for settings update 
        - name: _template
          rest_verbs: ["PUT", "GET", "DELETE"]
        - name: _update
          rest_verbs: ["POST"]
        - name: _create
          rest_verbs: ["POST"]
        - name: _field_caps
          rest_verbs: ["POST"]